config/routes.rb
Rails.application.routes.draw do
  # get 'topics/new'
  # get 'sessions/new'
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :topics
  
  get 'comments/new'
  post '/comments', to: 'comments#create'
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorite', to: 'favorites#destroy'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  PASSWORD_VALIDATION=/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i
  EMAIL_VALIDATION=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  
  validates :description, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :topic
  
end

app/models/topic.rb
class Topic < ApplicationRecord
  
  validates :user_id, presence: true
  
  validates :description, presence: true
  
  validates :image, presence: true
  
  belongs_to :user
  
  has_many :favorites
  
  has_many :favorite_users, through: :favorites, source: 'user'
  
  has_many :comments
  has_many :comment_users, through: :comments, source: 'user'
  
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
 
  validates :name , length: {in: 1..15}
  
  validates :password ,format: {with: PASSWORD_VALIDATION}
  
  validates :email ,format: {with: EMAIL_VALIDATION}
  
  # 定数を使わない場合
  # validates :password ,format: {with:/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i}
  # validates :email ,format: {with:/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  
  has_secure_password
  
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  add_flash_types :success, :info, :warning, :danger, :white
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
  
  # 課題２  
  helper_method :current_user, :logged_in?
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
    @comment = Comment.new
    @comment.topic_id = params[:topic_id]
    @comment.user_id = current_user.id
    respond_to do |format| 
      format.html 
      format.js 
    end
  end  
  
  def create
    comment=current_user.comments.new(comment_params)
    
    if comment.save
      redirect_to topics_path, success: "コメントを登録しました"
    else
      redirect_to topics_path, danger: "コメント登録できませんでした"
    end
    
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:description, :topic_id, :user_id)
  end  

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end

  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]

    if favorite.save
      redirect_to topics_path, success: 'お気に入りに登録しました'
    else
      redirect_to topics_path, danger: 'お気に入りに登録に失敗しました'
    end
  end
  
  def destroy
    if Favorite.find_by(id: params[:favorite]).delete
      redirect_to topics_path, success: '削除しました'
    else
      redirect_to topics_path, danger: '削除に失敗しました'
    end
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    # flash[:success] = "登録に成功しました"
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    # binding.pry
    user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
 def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end
  
  private
  def log_in(user)
    session[:user_id] = user.id
  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # 課題１
  def session_params
    params.require(:session).permit( :email, :password)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.includes(:favorite_users, :comments, :comment_users)
    @comment = Comment.new
  end
 
  def new
    @topic = Topic.new
  end

  def created
    @topic = current_user.topics.new(topic_params)
    # 省略せずに書く
    # @topic=Topic.new(topic_params)
    # @topic.user_id=current_user.id

    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    
  @user = User.new(user_params)
  # binding.pry
  if @user.save
    redirect_to root_path, danger: '登録が完了しました'
  else
    flash.now[:success] = "登録に失敗しました"
    render :new
  end
  end
  
end
private
def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/point_helper.rb
module PointHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_new.html.erb
<%= form_for @comment do |f| %>
  <div class="form-group">
    <%= f.hidden_field :user_id, value: @comment.user_id %>
    <%= f.hidden_field :topic_id, value: @comment.topic_id %>
  </div>
  <%= f.text_area :description, class: 'form-control' %>
  <%= f.submit 'Your Comment', class: 'btn btn-black btn-block' %>
<% end %>

app/views/comments/new.js.erb
$('#comment_new<%= @comment.topic_id %>').html(
	'<%= escape_javascript(render :partial => 'new') %>'
);

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            
            
            <%= image_tag topic.image.url %>
            <% if !topic.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(topic_id: topic.id) , method: :post do %>
                <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon-white' %>
              <% end %>
              
            <% else %>
              <%= link_to favorite_path(favorite: topic.favorites.find_by(user_id: current_user.id)) , method: :delete do %>
                <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon-red' %>
              <% end %>
            <% end %>
            <%= topic.favorites.count %>
            

            <%= link_to comments_new_path(topic_id: topic.id), remote: true do %>
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <% end %>
            
            <h2>Comments</h2>
            
            <div id=<%= "comment_new#{topic.id}" %>></div>
            
            <p class="topic-text">
                <% topic.comments.each do |comment| %>
                  <p class="topic-text">
                  <%= comment.description %>
                  </p>
                <% end %>
            </p>
            
            
        　   <!--<#%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>-->
        　   
            <!--<p class="topic-text">-->
            <!--  <%#= topic.description %>-->
            <!--</p>-->
            
            <!--<p class="comment">-->
            <!--  コメント-->
            <!--</p>-->
            
            <!--<%# topic.comments.each do |comment| %>-->
            <!-- <p class="comment-text">-->
            <!--  <#%= comment.user.name %>-->
            <!--  <%#= comment.description %>-->
            <!-- </p>-->
            <!--<%# end %>-->
            
            <!--<%#= form_for @comment, url: comments_path do |f| %>-->
            <!-- <div class="form-group">-->
            <!--   <%#= f.hidden_field :topic_id, :value => topic.id %>-->
            <!--   <#%= f.label :コメント登録 %>-->
            <!--   <%#= f.text_area :description, class: "form-control" %>-->
            <!--   <%#= f.submit "登録"%>-->
            <!-- </div>-->
            <!--<%# end %> -->
            
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          <% if logged_in? %>
          
            <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
            
          <% end %>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign in</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path ,class: 'text-white' %>
      </div>
    </div>
  </div>
</div>